#!/bin/bash

# v0.1

# To get this to work FBB first has to be exporting to a file 
# For this to happen, add something like the following to
# forward.sys, or more practically, an include file that can
# then be "included" in forward.sys by means of a line like:
#
# < inc/dumps
#
# where 'inc' is a subdirectory within etc/ where forward.sys
# is located.
#
#
#
# Below are several dump outputs writing various bulletins to
# different files.  Each of these dummy-BBS callsigns 'DUMPA'
# etc need to be added to etc/bbs.sys, preferably at the bottom
# so that they are out of the way and can be expanded if put in
# reverse order, be sure not to introduce any new lines to bbs.sys!
# 
# inc/dumps:
#
#A DUMPA
#   P @
#   C /home/bpq/nodes/pe1rrr/fbb/var/ax25/fbb/export/all_bulls.out
#   G * 
#--------
#A DUMPB
#   P @
#   C /home/bpq/nodes/pe1rrr/fbb/var/ax25/fbb/export/eu_bulls.out
#   G EU 
#--------
#A DUMPC
#   P @
#   C /home/bpq/nodes/pe1rrr/fbb/var/ax25/fbb/export/ww_bulls.out
#   G WW 
#--------
#A DUMPD
#   P @
#   C /home/bpq/nodes/pe1rrr/fbb/var/ax25/fbb/export/usa_bulls.out
#   G USA
#--------
#A DUMPE
#   P @
#   C /home/bpq/nodes/pe1rrr/fbb/var/ax25/fbb/export/nld_bulls.out
#   G NLD
#--------

# Directory where FBB forwards into a dump file:
infiledir="/home/bpq/nodes/pe1rrr/fbb/var/ax25/fbb/export"

# Directory where you want to store the week-based archives:
exportdir="/home/bpq/common/fbbdos/archived/bbs_mail/ham"

# Usage: <specify export file>
# e.g ./archive_packet_mail nld_bulls.out
# Run the script only once per week, preferably at 23:59 on Sunday.
#
# Example crontab entry: make sure the user you run is under has
# write permisson to the $expordir above.
#
#
#55 23 * * SUN /home/bpq/bin/archive_packet_mail all_bulls.out > /dev/null 2>&1
#55 23 * * SUN /home/bpq/bin/archive_packet_mail usa_bulls.out > /dev/null 2>&1
#56 23 * * SUN /home/bpq/bin/archive_packet_mail ww_bulls.out > /dev/null 2>&1
#57 23 * * SUN /home/bpq/bin/archive_packet_mail eu_bulls.out > /dev/null 2>&1
#58 23 * * SUN /home/bpq/bin/archive_packet_mail nld_bulls.out > /dev/null 2>&1#


###############################73 PE1RRR#################################
infile="$1"
if [ -z $1 ] 
then
	echo "Need to specify which mail export file you want to archive"
	exit
else
	infilepath="${infiledir}/${1}"
	if ! [ -f ${infilepath} ]
	then 
		echo "Looks like there is nothing to archive"
		echo "${infilepath} doesn't seem to exist"
		exit
	fi
fi

date=`date +w%V_y%G`
outfile="${exportdir}/${date}_${infile}"
outzip="${outfile}.zip"
if ! [ -d ${infiledir} ]
then
	echo "Input file directory not found"
	echo "This needs to be where FBB is storing the exported mail"
	exit
	fi


if ! [ -d ${exportdir} ]
then
	echo "Creating export directory"
	mkdir -p ${exportdir}
	fi

if [ -f ${outzip} ]
then
	echo "Export archival already run this week... Aborting"
	exit
	fi


mv ${infilepath} ${outfile}
if zip ${outzip} ${outfile} 
then
	echo "Successfully created ${outzip}"
	if rm -f ${outfile}
	then
		echo "Cleaned up"
	else
		echo "There was a problem (permissions?) cleaning up ${outfile}"
	fi

else
	echo "Failed to create archive"
fi

